name: Publish on Docker Hub

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push ocpu base image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davidgohel/opencpu-base
          tags: "latest"
